version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: pruebas
     
     
    ports:
      - "3307:3306"
    volumes:
      - ./backup/bdpazzioli.sql:/docker-entrypoint-initdb.d/backup.sql
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: